/*
 * ==========================================================================
 * File         : encoders.h
 * Description  : 
 * Author       : Ricard
 * Date         : DD/MM/YYYY
 * Version      : V1
 * ==========================================================================
 * Additional Notes:
 * - 
 * - 
 * ==========================================================================
 */
#pragma once

// Pin conections
const int CA1 = 22; // Input signal A form encoder 1.
const int CB1 = 21; // Input signal B from encoder 1.

const int CA2 = 35; // Input signal A from encoder 2.
const int CB2 = 32; // Input signal B from encoder 2.

volatile int  n1    = 0; // counts for encoder 1.
volatile int  n2    = 0; // counts for encoder 1.

double P1 = 0; // Position in degrees motor 1
double P2 = 0; // Position in degrees motor2
double D1 = 0; // Motor 1 Distance moved in cm
double D2 = 0; // Motor 2 Distance moved in cm

const double pi =3.1416;
//const double diameter = 6.82; // Wheel radius in cm
const double diameter = 7;

double R = 890;
//double R = 937.2; // Resolution R = mH x s x r,
                  // mH = counts per motor rev (11),
                  // s = states generated by AB channels (4),
                  // r = gearBox reduction ratio (21.3)

void initializeEncoders();

void encoder1(void);
void encoder2(void);

void resetCounts();

double getRotation(int encoder);
double getDistance(int encoder);
